xp-values:
  FARMER:
    WHEAT: 0.2
    CARROTS: 0.3
    POTATOES: 0.2
    BEETROOTS: 0.3
    NETHER_WART: 0.4
    SWEET_BERRY_BUSH: 0.2
    COCOA: 0.2
    SUGAR_CANE: 0.1
    MELON: 0.3
    PUMPKIN: 0.3
    CACTUS: 0.1

  MINER:
    COAL_ORE: 0.3
    IRON_ORE: 0.4
    COPPER_ORE: 0.3
    GOLD_ORE: 0.7
    REDSTONE_ORE: 0.5
    LAPIS_ORE: 0.5
    DIAMOND_ORE: 1.0
    EMERALD_ORE: 1.0
    NETHER_QUARTZ_ORE: 0.5
    NETHER_GOLD_ORE: 0.4
    ANCIENT_DEBRIS: 3.0
    DEEPSLATE_COAL_ORE: 0.4
    DEEPSLATE_IRON_ORE: 0.5
    DEEPSLATE_COPPER_ORE: 0.4
    DEEPSLATE_GOLD_ORE: 0.8
    DEEPSLATE_REDSTONE_ORE: 0.6
    DEEPSLATE_LAPIS_ORE: 0.6
    DEEPSLATE_DIAMOND_ORE: 1.2
    DEEPSLATE_EMERALD_ORE: 1.2

  LUMBERJACK:
    OAK_LOG: 0.3
    BIRCH_LOG: 0.3
    SPRUCE_LOG: 0.3
    JUNGLE_LOG: 0.3
    ACACIA_LOG: 0.3
    DARK_OAK_LOG: 0.3
    MANGROVE_LOG: 0.3
    CHERRY_LOG: 0.3
