name: MinecraftPlugin
version: 1.0
main: MinecraftPlugin
api-version: 1.20
name: MyFirstPlugin
version: 1.0
main: MinecraftPlugin
api-version: 1.20
commands:
  heal:
    description: Heilt dich komplett
    usage: /heal
  jobs:
    description: Öffnet das Job-Selection Menu
    usage: /jobs select
  jobsrecipes:
    description: Öffnet das Rezepte-GUI für deinen Job
    usage: /jobsrecipes
